### ISSUE TITLE
Legacy branch issues, etc...

### ISSUE THREAD

**Issue by pexcn** [pexcn/hackintosh-amd-fx-series#1]
- [ ] Disk name macOS -> HighSierra

**Comment by shrikant2002** [comment]
I have the same motherboard and graphic card and using AMD_HighSierra_v3Unofficial.dmg but i'm not able to boot into the installer after loading completes display goes off with no signal i also tried to boot with flag nv_disable=1 please suggest me solution

**Comment by pexcn** [comment]
You need select correct config_*.plist. In addition, this program is no longer recommended, you had better use https://github.com/AMD-OSX/AMD_Vanilla

**Comment by shrikant2002** [comment]
i tried vanilla build high sierra but after installing nvidia webdriver it stuck on " ioconsoleusers gioscreenlockstate 3 " error loop I saw you are using the same config as mine pls guide me and send me your EFI 

thanks you very much

**Comment by pexcn** [comment]
I don't have much experience with hackintosh, currently I have not installed hackintosh.

**Comment by shrikant2002** [comment]
did u got it working before ?
with this guide?

**Comment by pexcn** [comment]
Yes it works.

reference:
https://forum.amd-osx.com/viewforum.php?f=24
https://forum.amd-osx.com/viewforum.php?f=52

**Comment by pexcn** [comment]
to be continue on new master branch...
