### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by pexcn** [pexcn/hackintosh-amd-fx-series#4]
no time for do https://discordapp.com/channels/249992304503291905/263757191608139779

**Comment by pexcn** [comment]
1. https://amd-osx.com/forum/viewtopic.php?f=61&t=10104&sid=30ba1a57bd7986780316257179f8d33c
2. https://amd-osx.com/forum/viewtopic.php?f=61&t=9993&sid=1fa9435dd8c7bf2cfc44faa94bef9f85
3. https://forum.amd-osx.com/viewtopic.php?t=9277
4. https://kirainmoe.com/blog/post/opencore-migration-experience/
5. https://dortania.github.io/OpenCore-Desktop-Guide/

**Comment by pexcn** [comment]
- [OpenCore0.5.5_EFI-AMD-FX-15h-Lajull.zip](https://github.com/pexcn/hackintosh-amd-fx-series/files/4563179/OpenCore0.5.5_EFI-AMD-FX-15h-Lajull.zip)
- https://github.com/mikigal/ryzen-hackintosh
- https://github.com/misifiksi/ryzentosh-highsierra/blob/master/README.md
- https://github.com/mipxx/OpenCoreEFI/blob/master/README.md
- https://github.com/yungtry/EFI/blob/master/README.md
- https://github.com/daliansky/OC-little

**Comment by marcinkk** [comment]
did you manage to fix this error: administrator is creating non-ejectable disk image??

**Comment by pexcn** [comment]
> did you manage to fix this error: administrator is creating non-ejectable disk image??

No, but you can try use other usb port.

**Comment by marcinkk** [comment]
are you planning to upgrade the repository hackintosh amd fx to opencore version 0.5.9?

**Comment by pexcn** [comment]
> are you planning to upgrade the repository hackintosh amd fx to opencore version 0.5.9?

Yes, but this EFI not working for my PC, and I no time for do it.
Pull request welcome.

**Comment by marcinkk** [comment]
I wanted to ask you to see my EFI catalog in my repository and write what you would change in the config.plist file. my configuration is amd fx-6100, asus m5a78l-m lx, gpu amd hd7870.

**Comment by pexcn** [comment]
> I wanted to ask you to see my EFI catalog in my repository and write what you would change in the config.plist file. my configuration is amd fx-6100, asus m5a78l-m lx, gpu amd hd7870.

You can fork and change it.

**Comment by marcinkk** [comment]
I wanted you to check my efi directory in my repository.

**Comment by pexcn** [comment]
Close. This hardware is obsolete and there is no point in continuing the work.
